name: release

on:
  push:
    tags:
      - "*"

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Build UI
        run:  cd ui && yarn install --ignore-engines && yarn build

      - name: Setup release environment
        env:
          RELEASE_TOKEN: ${{secrets.GORELEASER_ACCESS_TOKEN}}
          OWNER: ${{github.event.repository.owner.login}}
          PROJECT: ${{github.event.repository.name}}
        run: |-
          # image tags must be lowercase
          owner=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          project=$(echo "$PROJECT" | tr '[:upper:]' '[:lower:]')
          {
            echo "GITHUB_TOKEN=${RELEASE_TOKEN}"
            echo "GITHUB_USER=${owner}"
            echo "GITHUB_PROJECT=${project}"
            echo "DOCKER_CREDS_FILE=.docker-creds"
          } > .release-env
          echo "${owner}:${RELEASE_TOKEN}:ghcr.io" > .docker-creds

      - name: Release publish
        run: make release
